spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_everymind
    username: devkevin
    password: Teste123@!
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update